import './index.html';
import './img/113.png';
import './styles/styles.css';
// import './js/rest';
// import './js/spread';
// import './js/forOf';
// import './js/symbol';
// import './js/string';
// import './js/function';
// import './js/objects';
import './js/classes';
